site_name: Reading Collections
markdown_extensions: 
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite
    - footnotes
    - meta

plugins:
    - search:
        separator: '[\s\-\.]+$'
    - modified-awesome-pages:
        filename: pages.yml
        maximum_file_homepage: 20
        maximum_days_ahead: 365
    
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML

theme:
    name: mkdocs
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    custom_dir: custom/